            - name: 🚀 Super Ultra Typescript Deploy
  # You may pin to the exact commit or the version.
  # uses: zhjpwlj/ultimate-deploy-system@51264058fb36729c33eb34e1b8c6da261d4390aa
  uses: zhjpwlj/ultimate-deploy-system@v1.0.2
          
